---
- name: Add PHP Repository
  apt_repository: repo='ppa:ondrej/php5' state=present
  register: ppaphp

- name: Install PHP and PHP-FPM
  when: ppaphp|success
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
  - php5-fpm
  - php5-cli
  - php5-pgsql
  - php5-mysql
  - php5-sqlite
  - php5-curl
  - php5-gd
  - php5-mcrypt
  - php5-memcached
  notify:
    - Start PHP-FPM